Accessibility fixes:
mdbassit/Coloris pull request #72
Opened 2023-01-10 02:57 UTC by royeden

Hello, what really neat library :smile:

I was checking it out for inspiration for a personal project (that will use a similar x/y component, but not for color picking) and came across some minor accessibility issues that I tried to fix right here:
* keyboard hue picker out of bounds: The keyboard movement allowed for the hue selector to go out of bounds, this PR fixes that by applying the same contstrains as the pointer drag events.
* focus-visible: [`focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#browser_compatibility) is currently supported on all browsers, this removes overhead of modifying classes via `classList` and it's simpler (it also seems to simplify the selectors a bit more).
* Closing the picker with keyboard without compromising state: The `Esc` key would close the picker resetting it to it's previous state. This would clash on accessibility for keyboard only users, as it's the only way they have to close the dialog that pops up. (I left a comment just in case this should be reverted or you want to change the `revert` param on the `closePicker` function)

Also, I tested all this using a simple HTML file, it could maybe go inside an `examples/index.html` on the project:

```html
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="/dist/coloris.css">
</head>
<body>
  <input type="text" data-coloris>
  <script href="/dist/coloris.js"></script>
</body>
</html>
```

2023-01-10 06:15 UTC, mdbassit commented
Hello Roy, thank you for the kind words and for taking the time to debug this tool. I really appreciate it.

You are absolutely right about the color marker (that's what I called in the code anyway) going out of bounds when using the keyboard, thank you for the fix.

As for focus-visible, I'm aware that it is supported in all browsers, but it's still fairly new for most browsers, and some only implemented less than a year ago (Safari). I generally wait until a feature has been around for 4 years (arbitrary number) before I implement it and remove the old workarounds. I did a lot of work in Africa and Asia, and users in those regions tend to not update their browsers as often.

And lastly, there is actually a close button in the color picker that is not labeled but has an aria-label for people using a screen reader. But you are right that it is not useful for people who use keyboard navigation without a screen reader. I'll have to think of a way to make the close button obvious without compromising the sleek and simple design.

So in summary, I can only accept the out of bounds marker fix for now. Could I trouble you to resubmit a PR with only that fix?

Thanks,
M.

2023-01-10 12:57 UTC, royeden commented
No problem, I've updated the code & the comment!

2023-01-11 02:00 UTC, melloware commented
So to follow up how do we close the popup with keyboard only?   Or that needs to be figured out?

2023-01-11 02:38 UTC, mdbassit requested changes
Could you please remove the dist files from the commit?

2023-01-11 02:49 UTC, mdbassit commented
> So to follow up how do we close the popup with keyboard only? Or that needs to be figured out?

Right now, the close button is not obvious unless you use a screen reader.

<img width="217" alt="Screenshot 2023-01-11 at 10 40 23" src="https://user-images.githubusercontent.com/6975607/211705852-92d0185e-822d-4056-8fd2-3c704d10a11b.png">

Maybe I can add an optional more obvious close button similar to the optional clear button. Here is what the clear button looks like today:

<img width="226" alt="Screenshot 2023-01-11 at 10 46 26" src="https://user-images.githubusercontent.com/6975607/211706322-410e2fa5-1258-4a9d-9995-99ee7e4c8a01.png">

Any thoughts @melloware, @royeden?

2023-01-11 03:53 UTC, royeden commented
Yes please, a visible close button would be great!

How would you distinguish between using that button and using `Escape`? Does `Escape` still reset state?

2023-01-11 04:10 UTC, royeden commented on src/coloris.js
> +    colorMarker.focus()
Focus usually goes to the component you interacted with your mouse, this happens with any input, but I was thinking more about input with `type="range"`, so I was confused to find that pointer interactions didn't set focus on `color marker`.

In regards to showing the focus ring, all my ideas rely on redundancy and emulating `:focus-visible`, so I'm not absolutely sure which one to pick, leaving them here for future reference :

```js
// Option 1: After focusing the colorMarker 
colorMarker.addEventListener("focus", () => picker.classList.add('clr-keyboard-nav'))

// Option 2: In moveMarker after focusing the colorMarker:
function moveMarker(event) {
  /* rest of the code */
  // After moving the marker, it should remain focused
  colorMarker.focus()
  picker.classList.add('clr-keyboard-nav')
}

// Option 3: In moveMarkerOnKeydown:
function moveMarkerOnKeydown(offsetX, offsetY) {
  /* anywhere as order is not important for this action*/
  picker.classList.add('clr-keyboard-nav')
}
```

2023-01-11 04:13 UTC, royeden commented
> Could you please remove the dist files from the commit?

Done!

2023-01-11 12:25 UTC, melloware commented
@mdbassit Not sure if this helps but this DatePicker I use Has the buttons Clear and Close at the bottom on opposite sides...

![image](https://user-images.githubusercontent.com/4399574/211805826-a08d1c46-f9af-484c-b772-fb44de224489.png)

2023-01-12 08:21 UTC, mdbassit approved these changes
I removed the call to `focus()' on the color marker

2023-01-12 08:23 UTC, merged

2023-01-12 08:39 UTC, mdbassit commented
@royeden I just pushed a commit to make sure the focus rings are always visible when using the keyboard. This commit also focuses the marker when moved like you suggested.

2023-01-12 08:41 UTC, mdbassit commented
> Yes please, a visible close button would be great!
> 
> How would you distinguish between using that button and using `Escape`? Does `Escape` still reset state?

`Escape` will still reset the state since the role of that key is to interrupt and/or reset. I'm working on adding an optional visible close button.

2023-01-12 13:02 UTC, melloware commented
Nice work!

2023-01-14 06:32 UTC, mdbassit commented
I just pushed a new release (v0.17.0) that adds an optional visible close button.

2023-01-14 15:58 UTC, melloware commented
0.17.0 deployed to NPM as well!

2023-01-20 09:51 UTC, mdbassit commented
@melloware I stupidly introduced a bug in v0.17.0 that I fixed in v0.17.1. Could I trouble you to update the NPM version to include the bugfix?

2023-01-20 12:19 UTC, melloware commented
Done!

2023-01-20 12:24 UTC, mdbassit commented
Thanks a lot!